name: Release Carbone Docker

on:
 # workflow_dispatch:
#  release:
#    types: [published]
  push:
    branches:    
    - docker_build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4

    - 
      name: Get Carbone version 
      run: echo "PACKAGE_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

    - 
      name: Get Carbone binary
      uses: robinraju/release-downloader@v1.9
      with:
        tag: ee-${{ env.PACKAGE_VERSION }}
        fileName: "*-linux"
        out-file-path: docker
        token: ${{ secrets.GITHUB_TOKEN }}

    -
      name: Rename Carbone binary
      run: mv docker/carbone-ee-${{ env.PACKAGE_VERSION }}-linux docker/carbone-ee-linux
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./docker
        file: ./docker/Dockerfile
        push: false
        tags: ${{ vars.DOCKERHUB_ORG }}/carbone-ee:${{ env.PACKAGE_VERSION }},${{ vars.DOCKERHUB_ORG }}/carbone-ee:latest