name: njsscan
on:
  pull_request:
    branches: [ master, main, enterprise-edition-master ]
jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan check
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: 'lib/* formatters/* bin/* studio/*'